flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.2.5.2
- QuickCheck-2.8.2
- aeson-0.8.1.1
- aeson-pretty-0.7.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- attoparsec-0.13.0.1
- cmdargs-0.10.13
- constraints-0.6
- dlist-0.7.1.2
- enclosed-exceptions-1.0.1.1
- exceptions-0.8.1
- hashable-1.2.4.0
- hspec-2.2.1
- hspec-core-2.2.1
- hspec-discover-2.2.1
- hspec-expectations-0.7.2
- lifted-async-0.8.0
- lifted-base-0.2.3.6
- monad-control-1.0.0.4
- monad-supply-0.6
- mtl-2.2.1
- optparse-applicative-0.11.0.2
- parsec-3.1.9
- primitive-0.6.1.0
- quickcheck-io-0.1.2
- random-1.1
- scientific-0.3.4.4
- setenv-0.1.1.3
- shelly-1.6.5
- stm-2.4.4.1
- syb-0.6
- system-fileio-0.3.16.3
- system-filepath-0.4.13.4
- text-1.2.2.0
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unordered-containers-0.2.6.0
- vector-0.11.0.0
- zlib-0.6.1.1
resolver: ghc-7.10.3
